name: bobadex
description: "a pokedex for boba shops."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.2+1

environment:
  sdk: ">=3.10.0 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest versions available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  supabase_flutter: ^2.9.1
  collection: ^1.19.1
  cached_network_image: ^3.3.0
  flutter_cache_manager: ^3.3.1
  provider: ^6.1.5
  flutter_svg: ^2.1.0
  extended_image: ^10.0.1
  url_launcher: ^6.3.2
  shared_preferences: ^2.5.5
  path_provider: ^2.1.5
  path: ^1.9.1
  firebase_core: ^4.1.0
  package_info_plus: ^10.2.1
  in_app_review: ^2.0.11
  flutter_native_splash: ^2.4.6
  go_router: ^18.0.0
  image: ^4.5.4
  uuid: ^4.5.1
  sentry_flutter: ^9.6.0
  firebase_analytics: ^12.0.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: lib/assets/logo.png
  # for android
  # adaptive_icon_foreground: assets/logo/app_icon_foreground.png
  # adaptive_icon_background: "#FFFFFF" 


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - lib/assets/icons/star.svg
    - lib/assets/icons/half_star.svg
    - lib/assets/icons/outlined_star.svg
    - lib/assets/icons/heart.svg
    - lib/assets/icons/heart_outlined.svg
    - lib/assets/icons/boba1.svg
    - lib/assets/icons/tapioca_pearls/pearl_outline.svg
    - lib/assets/icons/tapioca_pearls/pearl_half.svg
    - lib/assets/icons/tapioca_pearls/pearl_full.svg
    - lib/assets/default_icon.png
    - lib/assets/badges/
    - lib/assets/cities.json
    - lib/assets/logo.svg
    - lib/assets/logo.png
    - lib/assets/bobadex.svg
    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  fonts:
    - family: NotoSerif
      fonts:
        - asset: lib/assets/fonts/NotoSerif-SemiBold.ttf
          weight: 600

flutter_native_splash:
  color: "#E5BB7C"
  image: lib/assets/bobadex.png
  ios: true
  android: true
  android_12:
    color: "#E5BB7C"
    image: lib/assets/bobadex.png