// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHO7aUGOXvx75DCGzpuXvMQl-raBDot8g',
    appId: '1:342980802832:web:bb90c52519938312d54d95',
    messagingSenderId: '342980802832',
    projectId: 'bobadex',
    authDomain: 'bobadex.firebaseapp.com',
    storageBucket: 'bobadex.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQtvtJ0_bRdS2sSqc4b6wBeOn9EOxicNI',
    appId: '1:342980802832:android:f469914d69ce63c8d54d95',
    messagingSenderId: '342980802832',
    projectId: 'bobadex',
    storageBucket: 'bobadex.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOkTarfbYqTlC6VkE1lvEXXoa1smYhAuU',
    appId: '1:342980802832:ios:fbd36c65c18a7c32d54d95',
    messagingSenderId: '342980802832',
    projectId: 'bobadex',
    storageBucket: 'bobadex.firebasestorage.app',
    iosBundleId: 'com.hsiehleon.bobadex.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOkTarfbYqTlC6VkE1lvEXXoa1smYhAuU',
    appId: '1:342980802832:ios:f1cc8c14b040a0f3d54d95',
    messagingSenderId: '342980802832',
    projectId: 'bobadex',
    storageBucket: 'bobadex.firebasestorage.app',
    iosBundleId: 'com.hsiehleon.bobadex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHO7aUGOXvx75DCGzpuXvMQl-raBDot8g',
    appId: '1:342980802832:web:23a0001772252053d54d95',
    messagingSenderId: '342980802832',
    projectId: 'bobadex',
    authDomain: 'bobadex.firebaseapp.com',
    storageBucket: 'bobadex.firebasestorage.app',
  );
}
